# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3b062e67c1106444dec17195a5f6bbe2ac91904b8d252073b8b0e804b0a00df98bb8ee0634c18ff42b87e3c64522370d692df78c0d8368334181339b35bfbc7

test:
  secret_key_base: d458e029543faf849997a10db17f2d9b0c1b2acfc706b801993b4957b4493e12a59675bca36011cbddb46393637a4fcc5779bbd49c21d1290b3fe54a9650eae5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
